export interface DialCountry {
  code: string
  name: string
  dialCode: string
  flag: string
}

// Country-code list for the phone field.
// Priority: Egypt → Saudi Arabia → Arab countries → US & UK → rest of the world.
export const dialCountries: DialCountry[] = [
  { code: 'EG', name: 'مصر', dialCode: '+20', flag: '🇪🇬' },
  { code: 'SA', name: 'السعودية', dialCode: '+966', flag: '🇸🇦' },
  // Gulf & Arab countries
  { code: 'AE', name: 'الإمارات', dialCode: '+971', flag: '🇦🇪' },
  { code: 'QA', name: 'قطر', dialCode: '+974', flag: '🇶🇦' },
  { code: 'BH', name: 'البحرين', dialCode: '+973', flag: '🇧🇭' },
  { code: 'KW', name: 'الكويت', dialCode: '+965', flag: '🇰🇼' },
  { code: 'OM', name: 'عمان', dialCode: '+968', flag: '🇴🇲' },
  { code: 'JO', name: 'الأردن', dialCode: '+962', flag: '🇯🇴' },
  { code: 'IQ', name: 'العراق', dialCode: '+964', flag: '🇮🇶' },
  { code: 'LB', name: 'لبنان', dialCode: '+961', flag: '🇱🇧' },
  { code: 'SY', name: 'سوريا', dialCode: '+963', flag: '🇸🇾' },
  { code: 'PS', name: 'فلسطين', dialCode: '+970', flag: '🇵🇸' },
  { code: 'YE', name: 'اليمن', dialCode: '+967', flag: '🇾🇪' },
  { code: 'LY', name: 'ليبيا', dialCode: '+218', flag: '🇱🇾' },
  { code: 'TN', name: 'تونس', dialCode: '+216', flag: '🇹🇳' },
  { code: 'DZ', name: 'الجزائر', dialCode: '+213', flag: '🇩🇿' },
  { code: 'MA', name: 'المغرب', dialCode: '+212', flag: '🇲🇦' },
  { code: 'SD', name: 'السودان', dialCode: '+249', flag: '🇸🇩' },
  { code: 'MR', name: 'موريتانيا', dialCode: '+222', flag: '🇲🇷' },
  { code: 'DJ', name: 'جيبوتي', dialCode: '+253', flag: '🇩🇯' },
  { code: 'KM', name: 'جزر القمر', dialCode: '+269', flag: '🇰🇲' },
  { code: 'SO', name: 'الصومال', dialCode: '+252', flag: '🇸🇴' },
  // US & UK
  { code: 'US', name: 'الولايات المتحدة', dialCode: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'المملكة المتحدة', dialCode: '+44', flag: '🇬🇧' },
  // Rest of the world
  { code: 'DE', name: 'ألمانيا', dialCode: '+49', flag: '🇩🇪' },
  { code: 'FR', name: 'فرنسا', dialCode: '+33', flag: '🇫🇷' },
  { code: 'CA', name: 'كندا', dialCode: '+1', flag: '🇨🇦' },
  { code: 'AU', name: 'أستراليا', dialCode: '+61', flag: '🇦🇺' },
  { code: 'AF', name: 'أفغانستان', dialCode: '+93', flag: '🇦🇫' },
  { code: 'AL', name: 'ألبانيا', dialCode: '+355', flag: '🇦🇱' },
  { code: 'AD', name: 'أندورا', dialCode: '+376', flag: '🇦🇩' },
  { code: 'AO', name: 'أنغولا', dialCode: '+244', flag: '🇦🇴' },
  { code: 'AG', name: 'أنتيغوا وبربودا', dialCode: '+1268', flag: '🇦🇬' },
  { code: 'AR', name: 'الأرجنتين', dialCode: '+54', flag: '🇦🇷' },
  { code: 'AM', name: 'أرمينيا', dialCode: '+374', flag: '🇦🇲' },
  { code: 'AT', name: 'النمسا', dialCode: '+43', flag: '🇦🇹' },
  { code: 'AZ', name: 'أذربيجان', dialCode: '+994', flag: '🇦🇿' },
  { code: 'BS', name: 'الباهاما', dialCode: '+1242', flag: '🇧🇸' },
  { code: 'BD', name: 'بنغلاديش', dialCode: '+880', flag: '🇧🇩' },
  { code: 'BB', name: 'بربادوس', dialCode: '+1246', flag: '🇧🇧' },
  { code: 'BY', name: 'بيلاروسيا', dialCode: '+375', flag: '🇧🇾' },
  { code: 'BE', name: 'بلجيكا', dialCode: '+32', flag: '🇧🇪' },
  { code: 'BZ', name: 'بليز', dialCode: '+501', flag: '🇧🇿' },
  { code: 'BJ', name: 'بنين', dialCode: '+229', flag: '🇧🇯' },
  { code: 'BT', name: 'بوتان', dialCode: '+975', flag: '🇧🇹' },
  { code: 'BO', name: 'بوليفيا', dialCode: '+591', flag: '🇧🇴' },
  { code: 'BA', name: 'البوسنة والهرسك', dialCode: '+387', flag: '🇧🇦' },
  { code: 'BW', name: 'بوتسوانا', dialCode: '+267', flag: '🇧🇼' },
  { code: 'BR', name: 'البرازيل', dialCode: '+55', flag: '🇧🇷' },
  { code: 'BN', name: 'بروناي', dialCode: '+673', flag: '🇧🇳' },
  { code: 'BG', name: 'بلغاريا', dialCode: '+359', flag: '🇧🇬' },
  { code: 'BF', name: 'بوركينا فاسو', dialCode: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'بوروندي', dialCode: '+257', flag: '🇧🇮' },
  { code: 'CV', name: 'الرأس الأخضر', dialCode: '+238', flag: '🇨🇻' },
  { code: 'KH', name: 'كمبوديا', dialCode: '+855', flag: '🇰🇭' },
  { code: 'CM', name: 'الكاميرون', dialCode: '+237', flag: '🇨🇲' },
  { code: 'CF', name: 'جمهورية أفريقيا الوسطى', dialCode: '+236', flag: '🇨🇫' },
  { code: 'TD', name: 'تشاد', dialCode: '+235', flag: '🇹🇩' },
  { code: 'CL', name: 'تشيلي', dialCode: '+56', flag: '🇨🇱' },
  { code: 'CN', name: 'الصين', dialCode: '+86', flag: '🇨🇳' },
  { code: 'CO', name: 'كولومبيا', dialCode: '+57', flag: '🇨🇴' },
  { code: 'CG', name: 'الكونغو', dialCode: '+242', flag: '🇨🇬' },
  { code: 'CD', name: 'الكونغو الديمقراطية', dialCode: '+243', flag: '🇨🇩' },
  { code: 'CR', name: 'كوستاريكا', dialCode: '+506', flag: '🇨🇷' },
  { code: 'CI', name: 'ساحل العاج', dialCode: '+225', flag: '🇨🇮' },
  { code: 'HR', name: 'كرواتيا', dialCode: '+385', flag: '🇭🇷' },
  { code: 'CU', name: 'كوبا', dialCode: '+53', flag: '🇨🇺' },
  { code: 'CY', name: 'قبرص', dialCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'التشيك', dialCode: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'الدنمارك', dialCode: '+45', flag: '🇩🇰' },
  { code: 'DM', name: 'دومينيكا', dialCode: '+1767', flag: '🇩🇲' },
  { code: 'DO', name: 'الدومينيكان', dialCode: '+1809', flag: '🇩🇴' },
  { code: 'EC', name: 'الإكوادور', dialCode: '+593', flag: '🇪🇨' },
  { code: 'SV', name: 'السلفادور', dialCode: '+503', flag: '🇸🇻' },
  { code: 'GQ', name: 'غينيا الاستوائية', dialCode: '+240', flag: '🇬🇶' },
  { code: 'ER', name: 'إريتريا', dialCode: '+291', flag: '🇪🇷' },
  { code: 'EE', name: 'إستونيا', dialCode: '+372', flag: '🇪🇪' },
  { code: 'SZ', name: 'إسواتيني', dialCode: '+268', flag: '🇸🇿' },
  { code: 'ET', name: 'إثيوبيا', dialCode: '+251', flag: '🇪🇹' },
  { code: 'FJ', name: 'فيجي', dialCode: '+679', flag: '🇫🇯' },
  { code: 'FI', name: 'فنلندا', dialCode: '+358', flag: '🇫🇮' },
  { code: 'GA', name: 'الغابون', dialCode: '+241', flag: '🇬🇦' },
  { code: 'GM', name: 'غامبيا', dialCode: '+220', flag: '🇬🇲' },
  { code: 'GE', name: 'جورجيا', dialCode: '+995', flag: '🇬🇪' },
  { code: 'GH', name: 'غانا', dialCode: '+233', flag: '🇬🇭' },
  { code: 'GR', name: 'اليونان', dialCode: '+30', flag: '🇬🇷' },
  { code: 'GD', name: 'غرينادا', dialCode: '+1473', flag: '🇬🇩' },
  { code: 'GT', name: 'غواتيمالا', dialCode: '+502', flag: '🇬🇹' },
  { code: 'GN', name: 'غينيا', dialCode: '+224', flag: '🇬🇳' },
  { code: 'GW', name: 'غينيا بيساو', dialCode: '+245', flag: '🇬🇼' },
  { code: 'GY', name: 'غيانا', dialCode: '+592', flag: '🇬🇾' },
  { code: 'HT', name: 'هايتي', dialCode: '+509', flag: '🇭🇹' },
  { code: 'HN', name: 'هندوراس', dialCode: '+504', flag: '🇭🇳' },
  { code: 'HK', name: 'هونغ كونغ', dialCode: '+852', flag: '🇭🇰' },
  { code: 'HU', name: 'المجر', dialCode: '+36', flag: '🇭🇺' },
  { code: 'IS', name: 'آيسلندا', dialCode: '+354', flag: '🇮🇸' },
  { code: 'IN', name: 'الهند', dialCode: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'إندونيسيا', dialCode: '+62', flag: '🇮🇩' },
  { code: 'IR', name: 'إيران', dialCode: '+98', flag: '🇮🇷' },
  { code: 'IE', name: 'أيرلندا', dialCode: '+353', flag: '🇮🇪' },
  { code: 'IT', name: 'إيطاليا', dialCode: '+39', flag: '🇮🇹' },
  { code: 'JM', name: 'جامايكا', dialCode: '+1876', flag: '🇯🇲' },
  { code: 'JP', name: 'اليابان', dialCode: '+81', flag: '🇯🇵' },
  { code: 'KZ', name: 'كازاخستان', dialCode: '+7', flag: '🇰🇿' },
  { code: 'KE', name: 'كينيا', dialCode: '+254', flag: '🇰🇪' },
  { code: 'KR', name: 'كوريا الجنوبية', dialCode: '+82', flag: '🇰🇷' },
  { code: 'KG', name: 'قيرغيزستان', dialCode: '+996', flag: '🇰🇬' },
  { code: 'LA', name: 'لاوس', dialCode: '+856', flag: '🇱🇦' },
  { code: 'LV', name: 'لاتفيا', dialCode: '+371', flag: '🇱🇻' },
  { code: 'LS', name: 'ليسوتو', dialCode: '+266', flag: '🇱🇸' },
  { code: 'LR', name: 'ليبيريا', dialCode: '+231', flag: '🇱🇷' },
  { code: 'LI', name: 'ليختنشتاين', dialCode: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'ليتوانيا', dialCode: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'لوكسمبورغ', dialCode: '+352', flag: '🇱🇺' },
  { code: 'MG', name: 'مدغشقر', dialCode: '+261', flag: '🇲🇬' },
  { code: 'MW', name: 'مالاوي', dialCode: '+265', flag: '🇲🇼' },
  { code: 'MY', name: 'ماليزيا', dialCode: '+60', flag: '🇲🇾' },
  { code: 'MV', name: 'المالديف', dialCode: '+960', flag: '🇲🇻' },
  { code: 'ML', name: 'مالي', dialCode: '+223', flag: '🇲🇱' },
  { code: 'MT', name: 'مالطا', dialCode: '+356', flag: '🇲🇹' },
  { code: 'MX', name: 'المكسيك', dialCode: '+52', flag: '🇲🇽' },
  { code: 'MD', name: 'مولدوفا', dialCode: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'موناكو', dialCode: '+377', flag: '🇲🇨' },
  { code: 'MN', name: 'منغوليا', dialCode: '+976', flag: '🇲🇳' },
  { code: 'ME', name: 'الجبل الأسود', dialCode: '+382', flag: '🇲🇪' },
  { code: 'MZ', name: 'موزمبيق', dialCode: '+258', flag: '🇲🇿' },
  { code: 'MM', name: 'ميانمار', dialCode: '+95', flag: '🇲🇲' },
  { code: 'NA', name: 'ناميبيا', dialCode: '+264', flag: '🇳🇦' },
  { code: 'NP', name: 'نيبال', dialCode: '+977', flag: '🇳🇵' },
  { code: 'NL', name: 'هولندا', dialCode: '+31', flag: '🇳🇱' },
  { code: 'NZ', name: 'نيوزيلندا', dialCode: '+64', flag: '🇳🇿' },
  { code: 'NI', name: 'نيكاراغوا', dialCode: '+505', flag: '🇳🇮' },
  { code: 'NE', name: 'النيجر', dialCode: '+227', flag: '🇳🇪' },
  { code: 'NG', name: 'نيجيريا', dialCode: '+234', flag: '🇳🇬' },
  { code: 'MK', name: 'مقدونيا الشمالية', dialCode: '+389', flag: '🇲🇰' },
  { code: 'NO', name: 'النرويج', dialCode: '+47', flag: '🇳🇴' },
  { code: 'PK', name: 'باكستان', dialCode: '+92', flag: '🇵🇰' },
  { code: 'PA', name: 'بنما', dialCode: '+507', flag: '🇵🇦' },
  { code: 'PG', name: 'بابوا غينيا الجديدة', dialCode: '+675', flag: '🇵🇬' },
  { code: 'PY', name: 'باراغواي', dialCode: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'بيرو', dialCode: '+51', flag: '🇵🇪' },
  { code: 'PH', name: 'الفلبين', dialCode: '+63', flag: '🇵🇭' },
  { code: 'PL', name: 'بولندا', dialCode: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'البرتغال', dialCode: '+351', flag: '🇵🇹' },
  { code: 'RO', name: 'رومانيا', dialCode: '+40', flag: '🇷🇴' },
  { code: 'RU', name: 'روسيا', dialCode: '+7', flag: '🇷🇺' },
  { code: 'RW', name: 'رواندا', dialCode: '+250', flag: '🇷🇼' },
  { code: 'SN', name: 'السنغال', dialCode: '+221', flag: '🇸🇳' },
  { code: 'RS', name: 'صربيا', dialCode: '+381', flag: '🇷🇸' },
  { code: 'SG', name: 'سنغافورة', dialCode: '+65', flag: '🇸🇬' },
  { code: 'SK', name: 'سلوفاكيا', dialCode: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'سلوفينيا', dialCode: '+386', flag: '🇸🇮' },
  { code: 'ZA', name: 'جنوب أفريقيا', dialCode: '+27', flag: '🇿🇦' },
  { code: 'SS', name: 'جنوب السودان', dialCode: '+211', flag: '🇸🇸' },
  { code: 'ES', name: 'إسبانيا', dialCode: '+34', flag: '🇪🇸' },
  { code: 'LK', name: 'سريلانكا', dialCode: '+94', flag: '🇱🇰' },
  { code: 'SE', name: 'السويد', dialCode: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'سويسرا', dialCode: '+41', flag: '🇨🇭' },
  { code: 'TW', name: 'تايوان', dialCode: '+886', flag: '🇹🇼' },
  { code: 'TJ', name: 'طاجيكستان', dialCode: '+992', flag: '🇹🇯' },
  { code: 'TZ', name: 'تنزانيا', dialCode: '+255', flag: '🇹🇿' },
  { code: 'TH', name: 'تايلاند', dialCode: '+66', flag: '🇹🇭' },
  { code: 'TG', name: 'توغو', dialCode: '+228', flag: '🇹🇬' },
  { code: 'TR', name: 'تركيا', dialCode: '+90', flag: '🇹🇷' },
  { code: 'TM', name: 'تركمانستان', dialCode: '+993', flag: '🇹🇲' },
  { code: 'UG', name: 'أوغندا', dialCode: '+256', flag: '🇺🇬' },
  { code: 'UA', name: 'أوكرانيا', dialCode: '+380', flag: '🇺🇦' },
  { code: 'UY', name: 'أوروغواي', dialCode: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'أوزبكستان', dialCode: '+998', flag: '🇺🇿' },
  { code: 'VE', name: 'فنزويلا', dialCode: '+58', flag: '🇻🇪' },
  { code: 'VN', name: 'فيتنام', dialCode: '+84', flag: '🇻🇳' },
  { code: 'ZM', name: 'زامبيا', dialCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'زيمبابوي', dialCode: '+263', flag: '🇿🇼' },
]

export interface Nationality {
  code: string
  label: string
  flag: string
}

// Nationality field — Arab nationalities only.
// Order: Egyptian → Saudi → Emirati → Qatari → Bahraini → rest of the Arab nationalities.
export const arabNationalities: Nationality[] = [
  { code: 'EG', label: 'مصري', flag: '🇪🇬' },
  { code: 'SA', label: 'سعودي', flag: '🇸🇦' },
  { code: 'AE', label: 'إماراتي', flag: '🇦🇪' },
  { code: 'QA', label: 'قطري', flag: '🇶🇦' },
  { code: 'BH', label: 'بحريني', flag: '🇧🇭' },
  { code: 'KW', label: 'كويتي', flag: '🇰🇼' },
  { code: 'OM', label: 'عُماني', flag: '🇴🇲' },
  { code: 'JO', label: 'أردني', flag: '🇯🇴' },
  { code: 'IQ', label: 'عراقي', flag: '🇮🇶' },
  { code: 'LB', label: 'لبناني', flag: '🇱🇧' },
  { code: 'SY', label: 'سوري', flag: '🇸🇾' },
  { code: 'PS', label: 'فلسطيني', flag: '🇵🇸' },
  { code: 'YE', label: 'يمني', flag: '🇾🇪' },
  { code: 'LY', label: 'ليبي', flag: '🇱🇾' },
  { code: 'TN', label: 'تونسي', flag: '🇹🇳' },
  { code: 'DZ', label: 'جزائري', flag: '🇩🇿' },
  { code: 'MA', label: 'مغربي', flag: '🇲🇦' },
  { code: 'SD', label: 'سوداني', flag: '🇸🇩' },
  { code: 'MR', label: 'موريتاني', flag: '🇲🇷' },
  { code: 'DJ', label: 'جيبوتي', flag: '🇩🇯' },
  { code: 'KM', label: 'قمري', flag: '🇰🇲' },
  { code: 'SO', label: 'صومالي', flag: '🇸🇴' },
]
